"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var world_1 = require("world");
var Console_1 = require("@systems/console/Console");
var Stage_1 = require("@systems/stage/Stage");
var Input_1 = require("@systems/Input/Input");
var Welcome_1 = require("@systems/welcome/Welcome");
var Welcome_2 = require("@systems/welcome/messages/Welcome");
var LiXiaoYao_1 = require("@entities/players/LiXiaoYao");
var world = new world_1.World();
world.addSystem(Console_1.ConsoleSystem);
world.addSystem(Input_1.InputSystem);
world.addSystem(Stage_1.StageSystem);
world.addSystem(Welcome_1.WelcomeSystem);
world.addEntity(new LiXiaoYao_1.LiXiaoYao);
world.broadcast(new Welcome_2.Welcome());
